### ISSUE TITLE
Compatible with IV-3A ?

### ISSUE THREAD

**Issue by giganticlab** [ysard/PT6312_VFD_Arduino_Library#2] opened 2022-07-11 16:10 UTC
Hi, can i use this for my project using two tube IV-3A ?

**Comment by ysard** [comment] 2022-07-12 01:20
Hi, a priori yes, in theory I think your tube could be fed as I mention in the readme;

According to the "doc" on aliexpress (https://fr.aliexpress.com/item/4000320798282.html):

Nominal filament voltage, 0.7-1.0V
Constant voltage of the grid and segments, 20-30V

But you will need to use a driver like the one the library was designed (PT6312) to address the grid and segments of each of your tubes. You will also have to redefine the charset to adapt it to the segments you dispose of.

These drivers operate on negative voltages for inactive segments and grids and for filaments; something functional would give:

VFilament: -1V
VActive Grid & Segment: 5V (= VCC of the driver)
VInactive Grid & Segment: 0V/GND

Maybe this link (in French) will help you:
https://pro-domo.ddns.net/blog/afficheurs-fluorescents-vfd-branchement-partie-2.html

**Comment by giganticlab** [comment] 2022-07-12 05:57
Thanks you very much.... 🙏🙏🙏🙏

**Comment by giganticlab** [comment] 2022-07-12 09:20
So, filament dan VEE (PT6312) must be -(negative) when i use PT6312 and IV-3A?

**Comment by ysard** [comment] 2022-07-12 14:36
Yes, 1 filament pin must be at -1V (max for your tube), the other at GND.
The filaments should barely glow (this reduces their life span).
Inactive segments & grids must be at a much lower potential to reject electrons (-12 to -20V approximately) but in practice, to save a voltage regulator I noticed that using the common ground is enough.
The driver enables the elements with its own supply voltage: 5V.

**Comment by giganticlab** [comment] 2022-07-13 03:23
Is the basic schematic that I created is correct if implemented with IV-3A?
![Schematic_VFD IV-3A v3_2022-07-13](https://user-images.githubusercontent.com/97239487/178643888-abb8ab0e-211a-4ed9-a560-2b40fc5030fd.png)

I'm so sorry,  i ask too many questions.

**Comment by ysard** [comment] 2022-07-21 02:10
Hi, no problem, yes I think that your schematic would work.
Note: On the device I disassembled, STB, DIN/DOUT and CLK each had a 470 ohm resistor in series.
I don't really know the purpose of this.

**Comment by ysard** [comment] 2022-09-23 18:38
I close this issue since it seems to be solved.
I added the diagram on the readme with 1 resistor of 51K on the OSC pin as indicated in the datasheet.

**Closed as completed by ysard** 2022-09-23 18:38 UTC
